### PR TITLE
changed pgn format

### PR DESCRIPTION
**Pull request by Kraaft**
not familiar with github xD sorry you can delete this comment.

### CODE REVIEW

**Comment by forhavu** [comment]
This is PRing from my master branch which changed the code to work locally -- different from this repo which works directly with lichess.  This shouldn't be merged.  I did however open a pull request on the speed increase I managed.

**Comment by gbtami** [comment]
@forhavu I think this PR is cool. Maybe adding locally working code next to online working by switchable from a config (or command line) option can turn this PR pullable.

**Comment by forhavu** [comment]
@gbtami There's no need to PR my fork into this repo, just use my fork for running the service locally.

**Comment by gbtami** [comment]
I will do it. Thx for working on this!

**Pull request closed without merging**
